name: Generate terraform docs
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest # Run the workflow on the latest Ubuntu runner

    steps:
    - uses: actions/checkout@v3 # Check out the repository code

    - name: Install terraform Docs
      uses: terraform-docs/gh-actions@main # Action to generate Terrform documentation
      with:
        working-dir: Terraform   # Directory containing Terraform files
        output-file: README.md   # Update README.md with generated docs
        output-method: inject    # Inject docs into existing README.md
        git-push: "true"
